[project]
name = "alervis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14.6"
dependencies = [
    "gql[requests]>=4.0.0",
    "loguru>=0.7.3",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["lambda/test-skill",
            "lambda/google-health-test",
            "lambda/pbm-jira-summary",
            "rpi/halo-learn-server",
        ]
addopts = "--import-mode=importlib"

[tool.pyright]
extraPaths = ["lambda/test-skill",
        "lambda/google-health-test",
        "lambda/pbm-jira-summary",
        "rpi/halo-learn-server"
        ]
